---
title: "R Notebook"
output: html_notebook
---

# 1 - Ask

*Guiding questions*

* What is the problem you are trying to solve? 
* How can your insights drive business decisions?

### Key tasks
* Identify the business task 
* Consider key stakeholders

### Deliverable 
* A clear statement of the business task

# 2 - Prepare

*Guiding questions*

* Where is your data located and how is the data organized? 
* Are there issues with bias or credibility in this data? 
* Does your data ROCCC - Reliable, Original, Comprehensive, Current and Credible? 
* How are you addressing licensing, privacy, security, and accessibility? 
* How did you verify the data’s integrity? 
* How does it help you answer your question? 
* Are there any problems with the data?

### Key tasks
* Download data and store it appropriately 
* Identify how it’s organized
* Sort and filter the data
* Determine the credibility of the data

### Deliverable 
* A description of all data sources used

# 3 - Process

*Guiding questions*

* What tools are you choosing and why?
* Have you ensured your data’s integrity?
* What steps have you taken to ensure that your data is clean? 
* How can you verify that your data is clean and ready to analyze? 
* Have you documented your cleaning process so you can review and share those results?

### Key tasks
* Check the data for errors 
* Choose your tools
* Transform the data so you can work with it effectively
* Document the cleaning process.

### Deliverable 
* Documentation of any cleaning or manipulation of data

# 4 - Analyze

*Guiding questions*

* How should you organize your data to perform analysis on it? 
* Has your data been properly formatted? 
* What surprises did you discover in the data? 
* What trends or relationships did you find in the data? 
* How will these insights help answer your business questions?

### Key tasks
* Aggregate your data so it’s useful and accessible
* Organize and format your data
* Perform calculations
* Identify trends and relationships

### Deliverable 
* A summary of your analysis

# 5 - Share

*Guiding questions*

* Were you able to answer the question of how annual members and casual riders use Cyclistic bikes differently? 
* What story does your data tell? 
* How do your findings relate to your original question? 
* Who is your audience? What is the best way to communicate with them? 
* Can data visualization help you share your findings? 
* Is your presentation accessible to your audience?

### Key tasks
* Determine the best way to share your findings. 
* Create effective data visualizations. 
* Present your findings. 
* Ensure your work is accessible.

### Deliverable 
* Supporting visualizations and key findings

# 6 - Act

*Guiding questions*

* What is your final conclusion based on your analysis? 
* How could your team and business apply your insights? 
* What next steps would you or your stakeholders take based on your findings? 
* Is there additional data you could use to expand on your findings?

### Key tasks
* Create your portfolio
* Add your case study
* Practice presenting your case study to a friend or family member

### Deliverable 
* Your top three recommendations based on your analysis